services:
  - type: web
    name: mern-socialmedia-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://mern-socialmedia-app-sd1c.onrender.com/api